//written by Erin Gallagher
angular
.module('mainApp')
.constant('ConstantTextSerivce', {

	//this service stores all the contants text used throughout the app
	LOGIN : {
		INVALID_INITIAL_LOAD : 		{NAME : "could not retrieve all initial setup information" },
	},
	CALENDAR : {
		BUILDING_SELECTION : 		{NAME : "Select a Building" },
	},
	NAV_BAR : {
		CALENDAR : 		{NAME : "CALENDAR" },
		SEARCH : 		{NAME : "SEARCH" },
		MY_BOOKINGS : 	{NAME : "MY BOOKINGS" },
		ADMIN : 		{NAME : "ADMIN" },
		USERS : 		{NAME : "USERS" },
		GROUPS : 		{NAME : "GROUPS" },
		KEY_LIST : 		{NAME : "KEY LIST" },
		SIGN_OUT : 		{NAME : "SIGN OUT" },
	},
	SEARCH : {
		DATE_SELECTION : 	{NAME : "Date" },
		BUILDING_SELECTION :{NAME : "Building" },
		TIME_SELECTION : 	{NAME : "Time" },
		TIME_BETWEEN : 		{NAME : "To" },
		SEARCH_BUTTON : 	{NAME : "Search" },
		SEARCH_EXPLA : 		{NAME: "Search for Available Rooms"},
		NO_RESULTS : 		{NAME: "Your search returned no results."},
		
	},
	MY_BOOKINGS : {
		USER_INFO : 		{NAME : "User Information" },
		NAME : 				{NAME : "Name:" },
		EMAIL : 			{NAME : "Email:" },
		HOURS_REMAIN : 		{NAME : " Hours Remaining This Week: " },
		DATE : 				{NAME : "Date" },
		TIME : 				{NAME: "Time"},
		BUILDING : 			{NAME: "Building"},
		ROOM_NUM : 			{NAME: "Room Number"},
		KEY_REQ : 			{NAME: "Key Required"},
		REASON : 			{NAME: "Reason"},
		CLICK_CANCEL : 		{NAME: "Click to Cancel"},
		MY_BOOKINGS : 		{NAME: "My Bookings"},
		MY_REC_BOOKINGS : 	{NAME: "My Recurring Bookings"},
		REC_INFO : 			{NAME: "Click Row To Expand Recurring Bookings"},
		DAY_WEEK : 			{NAME: "Day of the Week"},
		BOOKINGS_REMAIN : 	{NAME: "Bookings Remaining"},
		DEPARTMENT : 		{NAME: "Department:"},	
	},
	USERS : {
		UPLOAD_MUSIC : 		{NAME : "Upload Music List" },
		UPLOAD_DRAMA : 		{NAME : "Upload Drama List" },
		DOWNLOAD_MUSIC : 	{NAME : "Download Music Users" },
		DOWNLOAD_DRAMA : 	{NAME : "Download Drama Users" },
		USER_SEARCH_TITLE : {NAME : "Search For A User" },
		SEARCH_NETID : 		{NAME: "Enter NetID"},
		SEARCH_BUTTON : 	{NAME: "Search"},
		NETID : 			{NAME: "NetID"},
		NETID_NOT_FOUND : 	{NAME: "Not Found"},
		NETID_SARCH_RESULT :{NAME: "User Search For NetID"},
		NAME : 				{NAME: "Name:"},
		WEEKLY_HRS_REMAIN : {NAME: "Remaining Weekly Hours"},
		THIS_WEEK : 		{NAME: "This"},
		NEXT_WEEK : 		{NAME: "Next"},
		WEEK : 				{NAME: "Week:"},
		GROUPS : 			{NAME: "'s Groups"},
		GROUP_NAME : 		{NAME: "Group Name"},
		HOURS_TYPE : 		{NAME: "Hours Type"},
		HOURS_GIVEN : 		{NAME: "Hours Given"},
		SPEC_HRS_REMAIN : 	{NAME: "Special Hours Remaining"},
		START_DATE : 		{NAME: "Start Date"},
		END_DATE : 			{NAME: "End Date"},
		DURATION_RESTRICT : {NAME: "Restrict User Booking Duartion"},
	},
	POPUP_BOOK : {
		BUILDING : 				{NAME : "Building:" },
		ROOM_NUM : 				{NAME : "Room #:" },
		START_DATE : 			{NAME : "Start Date:" },
		START_TIME : 			{NAME : "Start Time:" },
		END_DATE : 				{NAME : "End Date:" },
		END_TIME : 				{NAME : "End Time: " },
		NUM_PEOPLE : 			{NAME : "Number of People:" },
		REASON : 				{NAME : "Reason:" },
		DESCRIPT : 				{NAME : "Description:" },
		ERROR_DESCR_EXCEED : 	{NAME : "You cannot exceed 150 characters in this field" },
		ERROR_DESCR_REQ : 		{NAME : "Please provide a description for your booking" },
		PERFORMANCE_TITLE : 	{NAME : "Performance Title:" },
		ERROR_PERFOR_REQ : 		{NAME : "A Performance title is required" },
		COURSE_CODE : 			{NAME : "Course Code:" },
		ERROR_COURSE_EXCEED : 	{NAME : "You cannot exceed 20 characters in this field" },
		ERROR_COURSE_REQ : 		{NAME : "A course code is required" },
		REC_BOOKING : 			{NAME : "Recurring Booking:" },
		NUM_WEEKS : 			{NAME : "Number of Weeks:" },
		ERROR_WEEKS_MAX : 		{NAME : "The number of weeks cannot exceed" },
		ERROR_WEEKS_MIN : 		{NAME : "The number of weeks must exceed 1" },
		ERROR_WEEKS_REQ : 		{NAME : "Please provide a number of weeks" },
		ERROR_WEEKS_VALID : 	{NAME : "not a valid number" },
		BACK_BUTTON : 			{NAME : "Back" },
		BOOK_BUTTON : 			{NAME : "Book Room" },
	},
	POPUP_ROOM_INFO : {
		BUILDING : 		{NAME : "Building:" },
		ROOM_NUM : 		{NAME : "Room #:" },
		CAPACITY : 		{NAME : "Capacity:" },
		FEE : 		{NAME : "Fee:" },
		REQ_KEY : 		{NAME : "Requires Key:" },
		ROOM_SETUP : 		{NAME : "Room Setup:" },
		CONTENTS : 		{NAME : "Contents:" },
		BUILDING_HRS : 		{NAME : "Building Hours:" },
		EXIT_BUTTON : 		{NAME : "Exit" },

	},
	POPUP_VIEW_BOOKING : {
		BOOKING_INFO_TITLE : 	{NAME : "Booking Information" },
		BUILDING : 				{NAME : "Building:" },
		ROOM_NUM : 				{NAME : "Room #:" },
		DATE : 					{NAME : "Date:" },
		TIME : 					{NAME : "Time:" },
		NUM_PEOPLE : 			{NAME : "Number of People:" },
		REASON : 				{NAME : "Reason:" },
		DESCRIPT : 				{NAME : "Description:" },
		PERFORMANCE_TITLE : 	{NAME : "Performance Title:" },
		COURSE_CODE : 			{NAME : "Course Code:" },
		BOOKING_USER_INFO : 	{NAME : "Booking User Information" },
		NAME : 					{NAME : "Name:" },
		TYPE : 					{NAME : "Type:" },
		EMAIL : 				{NAME : "Email:" },
		CANCEL_BUTTON : 		{NAME : "Cancel Booking" },
		BACK_BUTTON : 			{NAME : "Back" },
	},
	POPUP_CONFIRM : {
		BUILDING : 				{NAME : "Building:" },
		ROOM_NUM : 				{NAME : "Room #:" },
		DATE : 					{NAME : "Date:" },
		TIME : 					{NAME : "Time:" },
		NUM_PEOPLE : 			{NAME : "Number of People:" },
		REASON : 				{NAME : "Reason:" },
		DESCRIPT : 				{NAME : "Description:" },
		PERFORMANCE_TITLE : 	{NAME : "Performance Title:" },
		COURSE_CODE : 			{NAME : "Course Code:" },
		OK_BUTTON : 			{NAME : "OK" },
		SUCCESSFUL_BOOKINGS : 	{NAME : "Successful Bookings:" },
		FAILED_BOOKINGS : 		{NAME : "Failed Bookings:" },
		CONTINUE_BUTTON : 		{NAME : "Continue with successful bookings" },
		OK_BUTTON : 			{NAME : "Ok" },
		CANCEL_BOOKING : 		{NAME : "Cancel All Bookings" },

	}

});
